# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# Density.py
# Created on: 2017-09-14 04:51:21.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: Density <Place> <Population> <Place_dissolved> <Households> 
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Script arguments
Place = arcpy.GetParameterAsText(0)

Population = arcpy.GetParameterAsText(1)

Place_dissolved = arcpy.GetParameterAsText(2)
if Place_dissolved == '#' or not Place_dissolved:
    Place_dissolved = "C:\\Graham_RR\\New File Geodatabase.gdb\\g9" # provide a default value if unspecified

Households = arcpy.GetParameterAsText(3)

# Local variables:
Modified_Input_Features = Place_dissolved
Output_Feature_Class = Modified_Input_Features
g9 = Output_Feature_Class
Output_Feature_Class__2_ = g9
g9__3_ = Output_Feature_Class__2_
g9__2_ = Output_Feature_Class__2_
g9__4_ = g9__2_
g9__5_ = g9__4_
g9__6_ = g9__5_
g9__7_ = g9__6_
g9__8_ = g9__7_

# Process: Dissolve
arcpy.Dissolve_management(Place, Place_dissolved, "", "", "MULTI_PART", "DISSOLVE_LINES")

# Process: Add Geometry Attributes
arcpy.AddGeometryAttributes_management(Place_dissolved, "AREA", "", "SQUARE_KILOMETERS", "")

# Process: Add Field
arcpy.AddField_management(Modified_Input_Features, "Population", "FLOAT", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Field
arcpy.CalculateField_management(Output_Feature_Class, "Population", "%Population%", "VB", "")

# Process: Add Field (2)
arcpy.AddField_management(g9, "Households", "FLOAT", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Field (2)
arcpy.CalculateField_management(Output_Feature_Class__2_, "Households", "%Households%", "VB", "")

# Process: Add Field (3)
arcpy.AddField_management(Output_Feature_Class__2_, "Persons_Per_HH", "FLOAT", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Field (3)
arcpy.CalculateField_management(g9__2_, "Persons_Per_HH", "(%Population% / 1.00) / (%Households% / 1.00)", "VB", "")

# Process: Add Field (4)
arcpy.AddField_management(g9__4_, "Population_Density", "FLOAT", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Field (4)
arcpy.CalculateField_management(g9__5_, "Population_Density", "[Population] / [POLY_AREA]", "VB", "")

# Process: Add Field (5)
arcpy.AddField_management(g9__6_, "Household_Density", "FLOAT", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Field (5)
arcpy.CalculateField_management(g9__7_, "Household_Density", "[Households] / [POLY_AREA]", "VB", "")

